### ISSUE TITLE
Wrong method declaration

### ISSUE THREAD

**Issue by sighsigh** [giu2000/FruitsStore#18]
https://github.com/giu2000/FruitsStore/blob/20d740917db3eff39953cbf9bf749f2ea3a53916/fruits_store/src/components/ProductDetails/ProductDetails.js#L27

volevo provare questa funzione di github per segnalare le cose da sistemare :D
i metodi si dichiarano così:
`methodName(args) { ... }`

se necessario appendi .bind(this) quando lo invochi

ciao!

**Comment by giu2000** [comment]
Questa funzione di github è fighissima!!
I gestori degli eventi, si possono dichiarare anche in questo modo, ' public class fields syntax,.
Ti evita di fare il bind nel costruttore
Lo dice la documentazione di react:  ' https://reactjs.org/docs/handling-events.html :)
