### ISSUE TITLE
AddToCartForm on submit

### ISSUE THREAD

**Issue by sighsigh** [giu2000/FruitsStore#19]
https://github.com/giu2000/FruitsStore/blob/20d740917db3eff39953cbf9bf749f2ea3a53916/fruits_store/src/components/ProductDetails/ProductDetails.js#L67

qua passi una prop "onSubmit" ma AddToCartForm riceve la prop "handleSubmit"...
sicura che stia funzionando?

**Comment by giu2000** [comment]
Funziona si!
Qui: https://redux-form.com/7.3.0/docs/faq/handlevson.md/
"redux-form covers handleSubmit functionality by providing a respective handler that you pass as a prop - that is, a handleSubmit method for you to pass to onSubmit.

With that in mind, you can think of the redux-form handleSubmit as a middle layer for your form's submit handler. Simply write your components as you normally would, passing handleSubmit where appropriate"

Funziona così il plugin.
Ma vedrò di usarne un altro che ti piace di più, ;)
